[package]
name = "scout"
version = "0.1.0"
authors = ["Lukas Herman <lukasman@amazon.com>"]
edition = "2021"

[dependencies]
esp-idf-sys = { version = "0.31.9", features = ["binstart"] }

[build-dependencies]
embuild = "0.30"
anyhow = "1"
